FROM node:14
# Env
ARG SERVER_PORT
ARG TYPEORM_USERNAME
ARG TYPEORM_PASSWORD
ARG TYPEORM_DATABASE
ARG TYPEORM_HOST
ARG TYPEORM_PORT
ARG TYPEORM_SYNCHRONIZE
ARG TYPEORM_DROP_SCHEMA
ARG TYPEORM_RUN_MIGRATION
ARG TYPEORM_LOG

ENV SERVER_PORT ${SERVER_PORT}
ENV TYPEORM_USERNAME ${TYPEORM_USERNAME}
ENV TYPEORM_PASSWORD ${TYPEORM_PASSWORD}
ENV TYPEORM_DATABASE ${TYPEORM_DATABASE}
ENV TYPEORM_HOST ${TYPEORM_HOST}
ENV TYPEORM_PORT ${TYPEORM_PORT}
ENV TYPEORM_SYNCHRONIZE ${TYPEORM_SYNCHRONIZE}
ENV TYPEORM_DROP_SCHEMA ${TYPEORM_DROP_SCHEMA}
ENV TYPEORM_RUN_MIGRATION ${TYPEORM_RUN_MIGRATION}
ENV TYPEORM_LOG ${TYPEORM_LOG}

# Create Directory for the Container
WORKDIR /usr/src/app
# Only copy the package.json file to work directory
COPY /package.json .
# Install all Packages
RUN npm install
# Copy all other source code to work directory
COPY . .
# TypeScript
#RUN npm run tsc
ENV NODE_PATH=./build
RUN npm run build
# Start
CMD ["npm", "start"]
EXPOSE 3000